//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookSales = new HashSet<BookSales>();
        }
    
        public int id { get; set; }
        public int CategoryID { get; set; }
        public int AuthorID { get; set; }
        public string BookName { get; set; }
        public string PublishingHouse { get; set; }
        public int PublishingYear { get; set; }
        public string Explanations { get; set; }
        public decimal Price { get; set; }
        public string ImagePath { get; set; }
        public int StockAmount { get; set; }
        public int SoldAmount { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<BookSales> BookSales { get; set; }
    }
}
