//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookShopDBContext : DbContext
    {
        public BookShopDBContext()
            : base("name=BookShopDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookSales> BookSales { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<DVD> DVD { get; set; }
        public virtual DbSet<DVD_Actor> DVD_Actor { get; set; }
        public virtual DbSet<DVDSales> DVDSales { get; set; }
        public virtual DbSet<MusicCD> MusicCD { get; set; }
        public virtual DbSet<MusicCDSales> MusicCDSales { get; set; }
        public virtual DbSet<Musician> Musician { get; set; }
    }
}
