//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVD
    {
        public DVD()
        {
            this.DVD_Actor = new HashSet<DVD_Actor>();
            this.DVDSales = new HashSet<DVDSales>();
        }
    
        public int id { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> DirectorID { get; set; }
        public string DVDName { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> IMDB { get; set; }
        public string Explanations { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImagePath { get; set; }
        public int StockAmount { get; set; }
        public int SoldAmount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Director Director { get; set; }
        public virtual ICollection<DVD_Actor> DVD_Actor { get; set; }
        public virtual ICollection<DVDSales> DVDSales { get; set; }
    }
}
