//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicCD
    {
        public MusicCD()
        {
            this.MusicCDSales = new HashSet<MusicCDSales>();
        }
    
        public int id { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> MusicianID { get; set; }
        public string MusicCDName { get; set; }
        public Nullable<int> Year { get; set; }
        public string Explanations { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ImagePath { get; set; }
        public int StockAmount { get; set; }
        public int SoldAmount { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Musician Musician { get; set; }
        public virtual ICollection<MusicCDSales> MusicCDSales { get; set; }
    }
}
